### ISSUE TITLE
Missing closing quotations in docker-compose.yml

### ISSUE THREAD

**Issue by lifan0127** [alan-johnson/docker-marklogic#2]
Hello Alan, thanks for your blog posts and code samples. I found closing quotations are missing at the following locations:

https://github.com/alan-johnson/docker-marklogic/blob/master/marklogic-automated/docker-compose.yml#L22

https://github.com/alan-johnson/docker-marklogic/blob/master/marklogic-automated/docker-compose.yml#L46

**Comment by alan-johnson** [comment]
How right you are, Dr. Li! Corrected now.
